services:
  notka:
    image: ghcr.io/razielel/notka-app:latest
    container_name: notka
    restart: unless-stopped
    env_file: .env
    ports:
      - "${NOTKA_HOST_PORT:-13379}:3000"
    volumes:
      - ./data:/data
